const Properties = {
  "Go": "None",
  "Old Kent Road": "Brown",
  "Community Chest": "None",
  "Whitechapel Road": "Brown",
  "Income Tax": "None",
  "King's Cross Station": "None",
  "The Angel Islington": "LightBlue",
  "Chance": "None",
  "Euston Road": "LightBlue",
  "Pentonville Road": "LightBlue",
  "Jail/Just Visiting": "None",
  "Pall Mall": "Pink",
  "Electric Company": "None",
  "Whitehall": "Pink",
  "Northumberland Avenue": "Pink",
  "Marylebone Station": "None",
  "Bow Street": "Orange",
  "Marlborough Street": "Orange",
  "Vine Street": "Orange",
  "Free Parking": "None",
  "Strand": "Red",
  "Fleet Street": "Red",
  "Trafalgar Square": "Red",
  "Fenchurch St Station": "None",
  "Leicester Square": "Yellow",
  "Coventry Street": "Yellow",
  "Water Works": "None",
  "Piccadilly": "Yellow",
  "Go To Jail": "None",
  "Regent Street": "Green",
  "Oxford Street": "Green",
  "Bond Street": "Green",
  "Liverpool Street Station": "None",
  "Park Lane": "Blue",
  "Super Tax": "None",
  "Mayfair": "Blue"
};

export default Properties;
